Improvements
apertium/apertium-tur-uzb pull request #3
Opened 2020-07-31 01:38 UTC by elmurod1202

2020-08-12 19:28 UTC, sevilaybayatli requested changes

2020-08-12 19:28 UTC, sevilaybayatli commented on apertium-tur-uzb.tur-uzb.dix
> +<e>       <p><l>Ä.<s n="abbr"/></l>                    <r>Ä.<s n="abbr"/></r></p></e>
this character does not exit in the Turkish alphabet

2020-08-12 19:28 UTC, sevilaybayatli commented on apertium-tur-uzb.tur-uzb.dix
> +<e>       <p><l>Temmuz<s n="n"/></l>                   <r>Iyul<s n="n"/></r></p></e>
Temmuz is July, is Iyul =July too?

2020-08-12 21:36 UTC, elmurod1202 commented on apertium-tur-uzb.tur-uzb.dix
> +<e>       <p><l>Ä.<s n="abbr"/></l>                    <r>Ä.<s n="abbr"/></r></p></e>
These actually exist in a Turkish lexc, so I thought it would be a good idea to include in a bidix too, since an abbreviation could be a loan one.

2020-08-12 21:37 UTC, elmurod1202 commented on apertium-tur-uzb.tur-uzb.dix
> +<e>       <p><l>Temmuz<s n="n"/></l>                   <r>Iyul<s n="n"/></r></p></e>
Yes, Iyul is July

2020-08-13 03:47 UTC, jonorthwash approved these changes

2020-08-13 03:47 UTC, jonorthwash commented on apertium-tur-uzb.tur-uzb.dix
> +<e>       <p><l>Ä.<s n="abbr"/></l>                    <r>Ä.<s n="abbr"/></r></p></e>
I think that's okay, yeah.

2020-08-13 03:47 UTC, merged